Test part two
Kidd254/To-Do-List pull request #8
Opened 2023-02-10 20:12 UTC by Kidd254

in this pull request me and my partner did the following: 

- Created a test file)for a file 
- wrote tests for the clear, completed and add to list functions
- used mock storage object to "imitate" localStorage operations

2023-02-10 21:32 UTC, vickymarz requested changes
Hi @Kidd254, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 

## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 21:32 UTC, vickymarz commented on src/modules/test/partTwo.test.js
> +describe('checkboxStatus', () => {
- [ ] One of your test seems to be failing. Kindly fix it 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/218202004-2e613e84-fcd3-48ee-8301-ee58f647946e.png)

2023-02-10 21:32 UTC, vickymarz commented on src/modules/test/partTwo.test.js
> +/* eslint-disable */
- [ ] Kindly ensure you dont disable any of the linters as linters helps to reduce bugs in your codebase and also focus you to write workable code. Please remove the linters you disabled

2023-02-11 07:08 UTC, OyePriscilla approved these changes
Hi @Kidd254 and @Eldonratzlaff 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Github Flow observed✔️
Linters Set up correctly ✔️ 
Descriptive PR summary and title ✔️ 
All test passed ✔️ 

## Required Changes ♻️

## Optional suggestions

- [optional] Please kindly add a working link to the live demo section of your README file (for both online version and presentation), if it's not available at the moment; kindly indicate **`NOT AVAILABLE AT THE MOMENT`**.. 👍  Thanks. 🙏 

- [optional] I observed that your third partner did not contribute to this milestone, kindly take note that your PR will be invalidated subsequently if perhaps such happen again. The essence of the collaboration is to prepare us ahead for our future job. 👍 

- [optional] Commit messages suppose to be in imperative tense and capitalized, please take note of this for subsequent PRs. Thanks. ✋   

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 23:35 UTC, merged